[package]
name = "advent2020"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im-rc = "15.1"
log = "0.4"
nom = "7.1"
num = "0.4"
ndarray = "0.15"
